Codestyle is changed according to eslint utility recommendations.
elshershnev/simple-logger pull request #1
Opened 2018-04-03 10:04 UTC by elshershnev

Code was changed by eslint utulity with --fix parameter and now looks much better.

2018-04-03 12:34 UTC, ubcent requested changes

2018-04-03 12:34 UTC, ubcent commented on loggers/logger.js
Why do you need so many empty lines?

2018-04-03 12:34 UTC, ubcent commented on loggers/logger.js
> +        }.bind(this));
I'd recommend you using arrow function instead of binding context here

2018-04-03 12:34 UTC, ubcent commented on loggers/logger.js
> +          logItemParts.push(String(logItem));
What the difference between these branches? In general it's the same

2018-04-03 12:34 UTC, ubcent commented on loggers/logger.js
> +        return Math.random() - 0.5;
Why do u need return here? As it seems to me, this style is more suitable:
```javascript
logItemId += logItemId.split('').filter(() => Math.random() - 0.5);
```

2018-04-04 04:50 UTC, elshershnev commented on loggers/logger.js
Fixed.

2018-04-04 04:50 UTC, elshershnev commented on loggers/logger.js
> +        }.bind(this));
Fixed.

2018-04-04 04:50 UTC, elshershnev commented on loggers/logger.js
> +          logItemParts.push(String(logItem));
Fixed.

2018-04-04 04:53 UTC, elshershnev commented on loggers/logger.js
> +        return Math.random() - 0.5;
Filter does't work if no returned value and I found a bug here! Changed code tologItemId += logItemId.split('').filter(() => {
+        return Math.random() - 0.5;

2018-04-05 09:05 UTC, ubcent approved these changes

2018-04-05 09:05 UTC, ubcent commented on loggers/logger.js
> +        return (Math.random() - 0.5) < 0;
In a previous review I meant something like following:
```javascript
logItemId += logItemId.split('').filter(() => (Math.random() - 0.5) < 0)
```

2018-04-05 09:16 UTC, elshershnev commented on loggers/logger.js
> +        return (Math.random() - 0.5) < 0;
Got it

2018-04-05 09:17 UTC, merged